Update PR Notification to filter by renovate branch prefix

diff --git a/.github/workflows/notify-google-chat.yml b/.github/workflows/notify-google-chat.yml
--- a/.github/workflows/notify-google-chat.yml
+++ b/.github/workflows/notify-google-chat.yml
@@ -3,14 +3,11 @@ name: PR Notification
 on:
   pull_request:
     types: [opened]
-    branches:
-      - feat/n1-prod-payments-k8s
-      - feat/prod-main-test
+
 
 jobs:
   notify-pr:
     runs-on: ubuntu-latest
-    if: startsWith(github.event.pull_request.head.ref, 'renovate/')
     steps:
       - name: Debug Workflow Trigger
         run: |
@@ -19,9 +16,7 @@ jobs:
           echo "Repository: $GITHUB_REPOSITORY"
           echo "PR Title: ${{ github.event.pull_request.title }}"
           echo "PR URL: ${{ github.event.pull_request.html_url }}"
-          echo "Head Ref: ${{ github.event.pull_request.head.ref }}"
-          echo "Base Ref: ${{ github.event.pull_request.base.ref }}"
-
+          echo "Event Path Content: $(cat $GITHUB_EVENT_PATH || echo 'File not found')"
       - name: Google Chat PR Notification
         if: always()
         uses: SimonScholz/google-chat-action@main
